import * as fs from "node:fs";
import * as core from "@actions/core";
import * as github from "@actions/github";
import { addCommentReaction, closeIssue } from "../clients/github.js";
import { deleteJulesSession, sendJulesMessage } from "../clients/jules.js";
import { sendNotification } from "../clients/notifier.js";
import { gitOps } from "../infrastructure/git.js";

interface CommandContext {
	githubToken: string;
	julesApiKey: string;
	sessionName: string;
	issueNumber: number;
	commentId: number;
	webhookUrl: string | undefined;
	octokit: ReturnType<typeof github.getOctokit>;
	repo: typeof github.context.repo;
}

/**
 * Handles the orchestration of the /fix command.
 */
export const handleFixCommand = async (
	githubToken: string,
	julesApiKey: string,
	sessionName: string,
	issueNumber: number,
	commentId: number,
	webhookUrl: string | undefined,
) => {
	const context: CommandContext = {
		githubToken,
		julesApiKey,
		sessionName,
		issueNumber,
		commentId,
		webhookUrl,
		octokit: github.getOctokit(githubToken),
		repo: github.context.repo,
	};

	let success = false;

	try {
		await notifyStart(context);

		const fixes = await sendJulesMessage(
			julesApiKey,
			sessionName,
			"Generate a Pull Request fixing the outlined breaking changes.",
		);

		if (fixes.length === 0) {
			throw new Error("Jules AI did not return any file fixes.");
		}

		const branchName = `depsync/fix-issue-${issueNumber}`;
		applyFixesToDisk(fixes);
		pushFixesToGithub(context, branchName);

		const pr = await createFixPullRequest(context, branchName);

		success = true;
		await sendNotification(
			webhookUrl,
			`✅ Jules AI created PR #${pr.number} for issue #${issueNumber}.`,
		);
	} catch (error) {
		const msg = error instanceof Error ? error.message : String(error);
		await handleFailure(context, msg);
	} finally {
		await cleanup(context, success);
	}
};

/**
 * Notifies the user that the fix process has started.
 */
async function notifyStart(ctx: CommandContext) {
	const { octokit, repo, issueNumber, commentId } = ctx;
	await addCommentReaction(ctx.githubToken, commentId, "eyes");
	await octokit.rest.issues.createComment({
		owner: repo.owner,
		repo: repo.repo,
		issue_number: issueNumber,
		body: "🚀 Jules AI is generating code fixes and preparing a Pull Request...",
	});
}

/**
 * Writes the generated fixes to the local filesystem.
 */
function applyFixesToDisk(
	fixes: Array<{ filePath: string; fileContent: string }>,
) {
	for (const fix of fixes) {
		core.info(`📝 Applying fix to ${fix.filePath}...`);
		fs.writeFileSync(fix.filePath, fix.fileContent);
	}
}

/**
 * Handles Git operations to commit and push fixes.
 */
async function pushFixesToGithub(ctx: CommandContext, branchName: string) {
	const { githubToken, repo } = ctx;
	gitOps.configureUser();
	gitOps.createBranch(branchName);
	gitOps.commitAll("chore: automated dependency fix by depSync");

	const remoteUrl = `https://x-access-token:${githubToken}@github.com/${repo.owner}/${repo.repo}.git`;
	gitOps.push(remoteUrl, branchName, true);
}

/**
 * Creates the Pull Request on GitHub.
 */
async function createFixPullRequest(ctx: CommandContext, branchName: string) {
	const { octokit, repo, issueNumber } = ctx;
	core.info("🎁 Creating Pull Request...");
	const { data: pr } = await octokit.rest.pulls.create({
		owner: repo.owner,
		repo: repo.repo,
		title: `[depSync] Fix for Issue #${issueNumber}`,
		head: branchName,
		base: "main",
		body: `This PR was automatically generated by Jules AI in response to issue #${issueNumber}.\n\nCloses #${issueNumber}`,
	});
	return pr;
}

/**
 * Handles errors and notifies the user of failure.
 */
async function handleFailure(ctx: CommandContext, message: string) {
	const { octokit, repo, issueNumber } = ctx;
	core.error(`❌ Failed /fix flow: ${message}`);
	await octokit.rest.issues.createComment({
		owner: repo.owner,
		repo: repo.repo,
		issue_number: issueNumber,
		body: `❌ **Failed to generate PR**: ${message}`,
	});
}

/**
 * Cleans up the Jules session and optionally closes the issue.
 */
async function cleanup(ctx: CommandContext, success: boolean) {
	const { julesApiKey, sessionName, githubToken, issueNumber } = ctx;
	core.info("🧹 Cleaning up Jules session...");
	await deleteJulesSession(julesApiKey, sessionName).catch((e) =>
		core.warning(`Cleanup failed: ${e.message}`),
	);

	if (success) {
		core.info(`🔒 Closing issue #${issueNumber} after successful PR creation.`);
		await closeIssue(githubToken, issueNumber);
	} else {
		core.info(`🔓 Keeping issue #${issueNumber} open due to failure.`);
	}
}
