import * as fs from "node:fs";
import * as core from "@actions/core";
import * as github from "@actions/github";
import { addCommentReaction } from "../clients/github.js";
import {
	createJulesFixSession,
	deleteJulesSession,
	sendJulesMessage,
} from "../clients/jules.js";
import { parseIssueContext } from "../core/orchestrator/issue-context.js";
import { rebuildDriftFromIssueContext } from "../core/orchestrator/orchestrator.js";
import { gitOps } from "../infrastructure/git.js";

interface CommandContext {
	githubToken: string;
	julesApiKey: string;
	issueBody: string;
	issueNumber: number;
	commentId: number;
	octokit: ReturnType<typeof github.getOctokit>;
	repo: typeof github.context.repo;
	coreFrameworks: ReadonlySet<string>;
}

const notifyStart = async (ctx: CommandContext): Promise<void> => {
	const { octokit, repo, issueNumber, commentId } = ctx;
	await addCommentReaction(ctx.githubToken, commentId, "eyes");
	await octokit.rest.issues.createComment({
		owner: repo.owner,
		repo: repo.repo,
		issue_number: issueNumber,
		body: "🚀 depSync is rebuilding focused context and generating a Pull Request...",
	});
};

const applyFixesToDisk = (
	fixes: Array<{ filePath: string; fileContent: string }>,
): void => {
	for (const fix of fixes) {
		core.info(`📝 Applying fix to ${fix.filePath}...`);
		fs.writeFileSync(fix.filePath, fix.fileContent);
	}
};

const pushFixesToGithub = async (
	ctx: CommandContext,
	branchName: string,
): Promise<void> => {
	const { githubToken, repo } = ctx;
	gitOps.configureUser();
	gitOps.createBranch(branchName);
	gitOps.commitAll("chore: automated dependency fix by depSync");

	const remoteUrl = `https://x-access-token:${githubToken}@github.com/${repo.owner}/${repo.repo}.git`;
	gitOps.push(remoteUrl, branchName, true);
};

const createFixPullRequest = async (
	ctx: CommandContext,
	branchName: string,
): Promise<{ number: number }> => {
	const { octokit, repo, issueNumber } = ctx;
	core.info("🎁 Creating Pull Request...");
	const { data: pr } = await octokit.rest.pulls.create({
		owner: repo.owner,
		repo: repo.repo,
		title: `[depSync] Fix for Issue #${issueNumber}`,
		head: branchName,
		base: "main",
		body: `This PR was automatically generated by depSync in response to issue #${issueNumber}.\n\nCloses #${issueNumber}`,
	});
	return pr;
};

const handleFailure = async (
	ctx: CommandContext,
	message: string,
): Promise<void> => {
	const { octokit, repo, issueNumber } = ctx;
	core.error(`❌ Failed /fix flow: ${message}`);
	await octokit.rest.issues.createComment({
		owner: repo.owner,
		repo: repo.repo,
		issue_number: issueNumber,
		body: `❌ **Failed to generate PR**: ${message}`,
	});
};

const cleanup = async (
	julesApiKey: string,
	sessionName: string | undefined,
): Promise<void> => {
	if (!sessionName) return;

	core.info("🧹 Cleaning up Jules session...");
	await deleteJulesSession(julesApiKey, sessionName).catch((error) => {
		const message = error instanceof Error ? error.message : String(error);
		core.warning(`Cleanup failed: ${message}`);
	});
};

export const handleFixCommand = async (
	githubToken: string,
	julesApiKey: string,
	issueBody: string,
	issueNumber: number,
	commentId: number,
	coreFrameworks: ReadonlySet<string>,
): Promise<void> => {
	const context: CommandContext = {
		githubToken,
		julesApiKey,
		issueBody,
		issueNumber,
		commentId,
		octokit: github.getOctokit(githubToken),
		repo: github.context.repo,
		coreFrameworks,
	};

	let sessionName: string | undefined;

	try {
		await notifyStart(context);

		const issueContext = parseIssueContext(issueBody);
		const drift = await rebuildDriftFromIssueContext(
			issueContext,
			githubToken,
			coreFrameworks,
		);

		const session = await createJulesFixSession(
			julesApiKey,
			context.repo.owner,
			context.repo.repo,
			drift,
		);
		sessionName = session.name;

		const fixes = await sendJulesMessage(
			julesApiKey,
			session.name,
			"Generate the code changes required for this migration.",
		);

		if (fixes.length === 0) {
			throw new Error("Jules AI did not return any file fixes.");
		}

		const branchName = `depsync/fix-issue-${issueNumber}`;
		applyFixesToDisk(fixes);
		await pushFixesToGithub(context, branchName);
		await createFixPullRequest(context, branchName);
	} catch (error) {
		const message = error instanceof Error ? error.message : String(error);
		await handleFailure(context, message);
	} finally {
		await cleanup(julesApiKey, sessionName);
	}
};
