import { randomUUID } from "node:crypto";
import { rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import * as core from "@actions/core";
import * as github from "@actions/github";
import { addCommentReaction } from "../clients/github.js";
import {
	createJulesFixSession,
	deleteJulesSession,
	extractPatchArtifacts,
	listAllJulesActivities,
	resolveJulesSource,
	waitForJulesSession,
} from "../clients/jules.js";
import { parseIssueContext } from "../core/orchestrator/issue-context.js";
import { rebuildDriftFromIssueContext } from "../core/orchestrator/orchestrator.js";
import { GitPatchApplyError, gitOps } from "../infrastructure/git.js";

interface CommandContext {
	githubToken: string;
	julesApiKey: string;
	issueBody: string;
	issueNumber: number;
	commentId: number;
	octokit: ReturnType<typeof github.getOctokit>;
	repo: typeof github.context.repo;
	coreFrameworks: ReadonlySet<string>;
}

const notifyStart = async (ctx: CommandContext): Promise<void> => {
	const { octokit, repo, issueNumber, commentId } = ctx;
	await addCommentReaction(ctx.githubToken, commentId, "eyes");
	await octokit.rest.issues.createComment({
		owner: repo.owner,
		repo: repo.repo,
		issue_number: issueNumber,
		body: "🚀 depSync is rebuilding focused context and generating a Pull Request...",
	});
};

const createPatchFile = async (patch: string): Promise<string> => {
	const patchFilePath = join(tmpdir(), `depsync-${randomUUID()}.patch`);
	await writeFile(patchFilePath, patch, "utf-8");
	return patchFilePath;
};

const describePatch = (patch: string, activityName: string): string => {
	const diffLine = patch
		.split("\n")
		.find((line) => line.startsWith("diff --git "));
	return diffLine ?? activityName;
};

const applyPatchArtifactsSequentially = async (
	_ctx: CommandContext,
	patches: ReturnType<typeof extractPatchArtifacts>,
): Promise<void> => {
	let appliedAnyPatch = false;

	for (const patchArtifact of patches) {
		const patchLabel = describePatch(
			patchArtifact.patch,
			patchArtifact.activityName,
		);
		const patchFilePath = await createPatchFile(patchArtifact.patch);

		try {
			gitOps.applyPatchFile(patchFilePath, patchLabel);
			appliedAnyPatch = true;
		} catch (error) {
			if (appliedAnyPatch) {
				gitOps.restoreWorkingTree();
			}

			const message = error instanceof Error ? error.message : String(error);
			throw new GitPatchApplyError(
				patchLabel,
				`Patch ${patchLabel} from ${patchArtifact.activityName} failed: ${message}`,
			);
		} finally {
			await rm(patchFilePath, { force: true });
		}
	}

	if (!appliedAnyPatch) {
		return;
	}

	try {
		gitOps.regenerateLockfile();
	} catch (error) {
		gitOps.restoreWorkingTree();
		const message = error instanceof Error ? error.message : String(error);
		throw new Error(`Failed to regenerate lockfile: ${message}`);
	}
};

const pushFixesToGithub = async (
	ctx: CommandContext,
	branchName: string,
): Promise<void> => {
	const { githubToken, repo } = ctx;
	gitOps.configureUser();
	gitOps.createBranch(branchName);
	gitOps.commitAll("chore: automated dependency fix by depSync");

	const remoteUrl = `https://x-access-token:${githubToken}@github.com/${repo.owner}/${repo.repo}.git`;
	gitOps.push(remoteUrl, branchName, true);
};

const createFixPullRequest = async (
	ctx: CommandContext,
	branchName: string,
): Promise<{ number: number }> => {
	const { octokit, repo, issueNumber } = ctx;
	core.info("🎁 Creating Pull Request...");
	const { data: pr } = await octokit.rest.pulls.create({
		owner: repo.owner,
		repo: repo.repo,
		title: `[depSync] Fix for Issue #${issueNumber}`,
		head: branchName,
		base: "main",
		body: `This PR was automatically generated by depSync in response to issue #${issueNumber}.\n\nCloses #${issueNumber}`,
	});
	return pr;
};

const handleFailure = async (
	ctx: CommandContext,
	message: string,
): Promise<void> => {
	const { octokit, repo, issueNumber } = ctx;
	core.error(`❌ Failed /fix flow: ${message}`);
	await octokit.rest.issues.createComment({
		owner: repo.owner,
		repo: repo.repo,
		issue_number: issueNumber,
		body: `❌ **Failed to generate PR**: ${message}`,
	});
};

const cleanup = async (
	julesApiKey: string,
	sessionName: string | undefined,
): Promise<void> => {
	if (!sessionName) return;

	core.info("🧹 Cleaning up Jules session...");
	await deleteJulesSession(julesApiKey, sessionName).catch((error) => {
		const message = error instanceof Error ? error.message : String(error);
		core.warning(`Cleanup failed: ${message}`);
	});
};

export const handleFixCommand = async (
	githubToken: string,
	julesApiKey: string,
	issueBody: string,
	issueNumber: number,
	commentId: number,
	coreFrameworks: ReadonlySet<string>,
): Promise<void> => {
	const context: CommandContext = {
		githubToken,
		julesApiKey,
		issueBody,
		issueNumber,
		commentId,
		octokit: github.getOctokit(githubToken),
		repo: github.context.repo,
		coreFrameworks,
	};

	let sessionName: string | undefined;

	try {
		await notifyStart(context);

		const issueContext = parseIssueContext(issueBody);
		const drift = await rebuildDriftFromIssueContext(
			issueContext,
			githubToken,
			coreFrameworks,
		);
		const source = await resolveJulesSource(
			julesApiKey,
			context.repo.owner,
			context.repo.repo,
		);

		const session = await createJulesFixSession(julesApiKey, source, drift);
		sessionName = session.name;

		await waitForJulesSession(julesApiKey, session.name);
		const activities = await listAllJulesActivities(julesApiKey, session.name);
		const patches = extractPatchArtifacts(session.name, activities);
		await applyPatchArtifactsSequentially(context, patches);

		const branchName = `depsync/fix-issue-${issueNumber}`;
		await pushFixesToGithub(context, branchName);
		await createFixPullRequest(context, branchName);
	} catch (error) {
		const message = error instanceof Error ? error.message : String(error);
		await handleFailure(context, message);
	} finally {
		await cleanup(julesApiKey, sessionName);
	}
};
