import * as github from "@actions/github";
import type { AggregatedDrift } from "../core/orchestrator/orchestrator.utils.js";
import type { JulesSessionResponse } from "./jules.js";

export interface GitHubDependencies {
	getOctokit: (token: string) => ReturnType<typeof github.getOctokit>;
}

const defaultDependencies: GitHubDependencies = {
	getOctokit: github.getOctokit,
};

/**
 * Opens or updates a GitHub Issue for a specific dependency drift.
 * Ensures ONE issue per dependency as per the monorepo architecture rules.
 */
export const reportDriftAsIssue = async (
	token: string,
	drift: AggregatedDrift,
	julesSession: JulesSessionResponse,
	deps: GitHubDependencies = defaultDependencies,
): Promise<void> => {
	const octokit = deps.getOctokit(token);
	const { owner, repo } = github.context.repo;

	const title = `[depSync] Dependency Update: ${drift.dependencyName}`;

	// Check if an issue already exists for this dependency to avoid duplicates
	const { data: existingIssues } = await octokit.rest.issues.listForRepo({
		owner,
		repo,
		state: "open",
		creator: "app/github-actions", // Or the action's identifier
	});

	const existingIssue = existingIssues.find((i) => i.title === title);

	const body = formatIssueBody(drift, julesSession);

	if (existingIssue) {
		await octokit.rest.issues.update({
			owner,
			repo,
			issue_number: existingIssue.number,
			body,
		});
	} else {
		await octokit.rest.issues.create({
			owner,
			repo,
			title,
			body,
		});
	}
};

/**
 * Formats the issue body with high-density information:
 * Affected packages, Jules' session link, and the /fix call-to-action.
 */
const formatIssueBody = (
	drift: AggregatedDrift,
	julesSession: JulesSessionResponse,
): string => {
	const packageTable = Array.from(drift.payloads)
		.map((p) => {
			return `| ${p.package.packageName} | \`${p.update.currentVersion}\` | \`${p.update.latestVersion}\` | [${p.usages.length} usages] |`;
		})
		.join("\n");

	return `## 📦 Dependency Update Required: ${drift.dependencyName}

Jules has analyzed your monorepo and identified that ${drift.dependencyName} is out of sync across multiple services.

### 📊 Affected Packages
| Package | Current | Latest | AST Context |
| :--- | :--- | :--- | :--- |
${packageTable}

### 🤖 Jules Analysis Session
View the full autonomous analysis and proposed plan:
**[Jules Session: ${julesSession.title}](https://console.cloud.google.com/jules/sessions/${julesSession.name.split("/").pop()})**

---

### 🛠️ ChatOps Commands
Reply to this issue with one of the following commands:
- \`/fix\`: Trigger Jules to automatically generate a Pull Request with the required code fixes.
- \`/dry-run\`: See the proposed changes without creating a branch.

> This issue was generated by **depSync** — Context-Aware AI Dependency Manager.
<!-- jules-session-id: ${julesSession.name} -->`;
};
