import * as github from "@actions/github";
import type { AggregatedDrift } from "../core/orchestrator/orchestrator.utils.js";
import type { JulesSessionResponse } from "./jules.js";

export interface GitHubDependencies {
	getOctokit: (token: string) => ReturnType<typeof github.getOctokit>;
}

const defaultDependencies: GitHubDependencies = {
	getOctokit: github.getOctokit,
};

/**
 * Opens or updates a GitHub Issue for a specific dependency drift.
 * Ensures ONE issue per dependency as per the monorepo architecture rules.
 */
export const reportDriftAsIssue = async (
	token: string,
	drift: AggregatedDrift,
	julesSession: JulesSessionResponse,
	deps: GitHubDependencies = defaultDependencies,
): Promise<void> => {
	const octokit = deps.getOctokit(token);
	const { owner, repo } = github.context.repo;

	const title = `[depSync] Dependency Update: ${drift.dependencyName}`;

	// Check if an issue already exists for this dependency to avoid duplicates
	const { data: existingIssues } = await octokit.rest.issues.listForRepo({
		owner,
		repo,
		state: "open",
		creator: "app/github-actions", // Or the action's identifier
	});

	const existingIssue = existingIssues.find((i) => i.title === title);

	const body = formatIssueBody(drift, julesSession);

	if (existingIssue) {
		await octokit.rest.issues.update({
			owner,
			repo,
			issue_number: existingIssue.number,
			body,
		});
	} else {
		await octokit.rest.issues.create({
			owner,
			repo,
			title,
			body,
		});
	}
};

/**
 * Closes a GitHub issue.
 */
export const closeIssue = async (
	token: string,
	issueNumber: number,
	deps: GitHubDependencies = defaultDependencies,
): Promise<void> => {
	const octokit = deps.getOctokit(token);
	const { owner, repo } = github.context.repo;

	await octokit.rest.issues.update({
		owner,
		repo,
		issue_number: issueNumber,
		state: "closed",
	});
};

/**
 * Adds a reaction to an issue comment.
 */
export const addCommentReaction = async (
	token: string,
	commentId: number,
	reaction:
		| "eyes"
		| "hooray"
		| "heart"
		| "+1"
		| "-1"
		| "laugh"
		| "confused"
		| "rocket",
	deps: GitHubDependencies = defaultDependencies,
): Promise<void> => {
	const octokit = deps.getOctokit(token);
	const { owner, repo } = github.context.repo;

	await octokit.rest.reactions.createForIssueComment({
		owner,
		repo,
		comment_id: commentId,
		content: reaction === "eyes" ? "eyes" : reaction, // Map to GitHub's internal names if different
	});
};

/**
 * Formats the issue body with high-density information:
 * Release notes, affected packages with descriptions, Jules session, and ChatOps CTA.
 */
const formatIssueBody = (
	drift: AggregatedDrift,
	julesSession: JulesSessionResponse,
): string => {
	const packageTable = drift.payloads
		.map((p) => {
			const desc = p.package.serviceDescription || "_No description_";
			return `| ${p.package.packageName} | ${desc} | \`${p.update.currentVersion}\` | \`${p.update.latestVersion}\` | ${p.usages.length} usages |`;
		})
		.join("\n");

	const releaseNotesSection = drift.releaseNotes
		? `### 📋 Release Notes (\`${drift.latestVersion}\`)\n\n<details>\n<summary>Click to expand</summary>\n\n${drift.releaseNotes}\n\n</details>`
		: `### 📋 Release Notes\n\n_No release notes found for \`${drift.latestVersion}\`._`;

	return `## 📦 Dependency Update Required: ${drift.dependencyName}

depSync has analyzed your monorepo and identified that **${drift.dependencyName}** is out of sync across multiple services.

${releaseNotesSection}

### 📊 Affected Packages
| Package | Description | Current | Latest | AST Context |
| :--- | :--- | :--- | :--- | :--- |
${packageTable}

### 🤖 Jules Analysis Session
View the full autonomous analysis and proposed plan:
**[Jules Session: ${julesSession.title}](https://console.cloud.google.com/jules/sessions/${julesSession.name.split("/").pop()})**

---

### 🛠️ ChatOps Commands
Reply to this issue with one of the following commands:
- \`/fix\`: Trigger Jules to automatically generate a Pull Request with the required code fixes.
- \`/close\`: Terminate the Jules AI session and close this issue.

> This issue was generated by **depSync** — Context-Aware AI Dependency Manager.
<!-- jules-session-id: ${julesSession.name} -->`;
};
