import * as github from "@actions/github";
import { formatIssueContextComment } from "../core/orchestrator/issue-context.js";
import type {
	AggregatedDrift,
	DepSyncIssueAnalysis,
	DepSyncIssueContext,
} from "../types/drift.js";

export interface GitHubDependencies {
	getOctokit: (token: string) => ReturnType<typeof github.getOctokit>;
}

export interface DriftIssueReport {
	number: number;
	url: string;
}

const defaultDependencies: GitHubDependencies = {
	getOctokit: github.getOctokit,
};

const buildIssueContext = (
	drift: AggregatedDrift,
	analysis: DepSyncIssueAnalysis,
): DepSyncIssueContext => ({
	schemaVersion: 1,
	dependencyName: drift.dependencyName,
	currentVersions: Array.from(drift.currentVersions),
	latestVersion: drift.latestVersion,
	affectedPackages: drift.affectedPackages,
	affectedSourceFiles: drift.affectedSourceFiles,
	riskLevel: analysis.riskLevel,
	issueSummary: analysis.issueSummary,
	executionMetadata: analysis.executionMetadata,
});

const formatIssueBody = (
	drift: AggregatedDrift,
	analysis: DepSyncIssueAnalysis,
): string => {
	const packageTable = drift.payloads
		.map((payload) => {
			const desc = payload.package.serviceDescription || "_No description_";
			return `| ${payload.package.packageName} | ${desc} | ${payload.usages.length} files |`;
		})
		.join("\n");

	const hiddenContext = formatIssueContextComment(
		buildIssueContext(drift, analysis),
	);

	return `## Dependency Update Required: ${drift.dependencyName}

depSync detected an outdated dependency and prepared a compact remediation context for stateless follow-up automation.

### Impact
- Latest version: \`${drift.latestVersion}\`
- Current versions: ${Array.from(drift.currentVersions)
		.map((version) => `\`${version}\``)
		.join(", ")}
- Risk level: **${analysis.riskLevel.toUpperCase()}**

${analysis.markdown}

### Affected Packages
| Package | Description | Footprint |
| :--- | :--- | :--- |
${packageTable}

### ChatOps Commands
- \`/fix\`: Rebuild focused context, generate code changes, and open a Pull Request.
- \`/close\`: Close the issue and clean up any legacy session state if present.

> This issue was generated by **depSync**.
${hiddenContext}`;
};

/**
 * Opens or updates a GitHub Issue for a specific dependency drift.
 * Ensures one issue per dependency.
 */
export const reportDriftAsIssue = async (
	token: string,
	drift: AggregatedDrift,
	analysis: DepSyncIssueAnalysis,
	deps: GitHubDependencies = defaultDependencies,
): Promise<DriftIssueReport> => {
	const octokit = deps.getOctokit(token);
	const { owner, repo } = github.context.repo;
	const title = `[depSync] Dependency Update: ${drift.dependencyName}`;

	const { data: existingIssues } = await octokit.rest.issues.listForRepo({
		owner,
		repo,
		state: "open",
		creator: "app/github-actions",
	});

	const existingIssue = existingIssues.find((issue) => issue.title === title);
	const body = formatIssueBody(drift, analysis);

	if (existingIssue) {
		const { data } = await octokit.rest.issues.update({
			owner,
			repo,
			issue_number: existingIssue.number,
			body,
		});

		return { number: data.number, url: data.html_url };
	}

	const { data } = await octokit.rest.issues.create({
		owner,
		repo,
		title,
		body,
	});

	return { number: data.number, url: data.html_url };
};

export const getIssueBody = async (
	token: string,
	issueNumber: number,
	deps: GitHubDependencies = defaultDependencies,
): Promise<string> => {
	const octokit = deps.getOctokit(token);
	const { owner, repo } = github.context.repo;
	const { data } = await octokit.rest.issues.get({
		owner,
		repo,
		issue_number: issueNumber,
	});

	return data.body ?? "";
};

/**
 * Closes a GitHub issue.
 */
export const closeIssue = async (
	token: string,
	issueNumber: number,
	deps: GitHubDependencies = defaultDependencies,
): Promise<void> => {
	const octokit = deps.getOctokit(token);
	const { owner, repo } = github.context.repo;

	await octokit.rest.issues.update({
		owner,
		repo,
		issue_number: issueNumber,
		state: "closed",
	});
};

/**
 * Adds a reaction to an issue comment.
 */
export const addCommentReaction = async (
	token: string,
	commentId: number,
	reaction:
		| "eyes"
		| "hooray"
		| "heart"
		| "+1"
		| "-1"
		| "laugh"
		| "confused"
		| "rocket",
	deps: GitHubDependencies = defaultDependencies,
): Promise<void> => {
	const octokit = deps.getOctokit(token);
	const { owner, repo } = github.context.repo;

	await octokit.rest.reactions.createForIssueComment({
		owner,
		repo,
		comment_id: commentId,
		content: reaction === "eyes" ? "eyes" : reaction,
	});
};
